spring.application.name=boxing-fighter-management-app
spring.datasource.url=jdbc:mysql://boxing-app-database.cngcy0mqoo33.us-east-2.rds.amazonaws.com:3306/boxing_management
spring.datasource.username=admin
spring.datasource.password=Ui78gQt5c
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

